<?php

/**
 * Implementation of hook_help()
 */
function shapes_help($path, $arg) {
    switch($path) {
        case 'admin/help#sample' :
            return '<p>' . t('Sample help text') . '</p>';
            break;
    }
}


/**
 * Implementation of hook_perm()
 */
function shapes_perm() {
    return array(
        'administer sample page' => array(
            'title' => t('Administer shapes module'),
            'description' => t('Perform administration tasks for shapes module'),
        )
    );
}


/**
 * Implementation of hook_menu()
 */
function shapes_menu() {
    $items['shapes'] = array(
        'title' => 'Sample',
        'description' => t('Sample Shapes form'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shapes_form'),
        'access arguments' => array('administer sample page'),
        'type' => MENU_CALLBACK,
        'file' => 'shapes.forms.inc',
    );

    return $items;
}

/**
 * Api function to collect all the shapes.
 *
 * @return array
 */
function shapes_get_shapes() {

    $info = &drupal_static(__FUNCTION__, array());

    if (empty($info)) {
        $info = module_invoke_all('shapes_info');
    }
    return $info;
}

/**
 * Implements the hook_shapes_info.
 */
function shapes_shapes_info() {
    return array(
        'Circle',
        'Triangle',
        'Donut'
    );
}
